### ISSUE TITLE
Error during install - pyrender

### ISSUE THREAD

**Issue by andytriboletti** [huanngzh/threestudio-dreamwaltz#1]
Collecting pyrender (from -r requirements.txt (line 6))
  Downloading pyrender-0.1.45-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 3.7 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement open3d==0.17.0 (from versions: 0.18.0)
ERROR: No matching distribution found for open3d==0.17.0

I'm running Ubuntu with WSL

**Comment by andytriboletti** [comment]
I changed it to open3d==0.18.0 and it didn't complain

**Comment by huanngzh** [comment]
requirements.txt is the environment I use for testing. Other versions of packages may also run successfully.
