### ISSUE TITLE
[misc] support High-Resolution Canonical Avatars && image-to-avatars

### ISSUE THREAD

**Issue by xdobetter** [huanngzh/threestudio-dreamwaltz#3]
Hello, great job on your work! I have a couple of questions regarding it:

1. Can the current codebase support [High-Resolution Canonical Avatars](https://idea-research.github.io/DreamWaltz/#canonical_2)? What is its computational overhead compared to 64x64 avatars?

2. Can the current task accommodate image-to-avatar conversion?

**Comment by huanngzh** [comment]
1. I check the improvement of DreamWaltz about resolution. I think it can be easily reproduced in the current codebase by changing the resolution. I'm not sure about the specific computing resource consumption, and I haven't reproduced it yet :)
2. Maybe you can introduce some methods like zero123, IP-Adapter as guidance?

**Comment by xdobetter** [comment]
thank you very much for your patient reply，I also have another question about personalized Avatar generate use your backbone，specific information can be seen https://github.com/IDEA-Research/DreamWaltz/issues/12
---- Replied Message ----
From Zehuan ***@***.***> Date 05/02/2024 14:16 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [huanngzh/threestudio-dreamwaltz] [misc] support High-Resolution Canonical Avatars && image-to-avatars (Issue #3) 
I check the improvement of DreamWaltz about resolution. I think it can be easily reproduced in the current codebase by changing the resolution. I'm not sure about the specific computing resource consumption, and I haven't reproduced it yet :)
Maybe you can introduce some methods like zero123, IP-Adapter as guidance?

**Comment by huanngzh** [comment]
I think you need to adjust some parameters such as guidance_scale, weighting_strategy etc. In addition, in my code, there is a parameter `guidance_eval` in the config, which indicates how many steps to verify the image inference results. You can judge whether lora works based on this.

**Comment by huanngzh** [comment]
I think you need to adjust some parameters such as guidance_scale, weighting_strategy etc. In addition, in my code, there is a parameter `guidance_eval` in the config, which indicates how many steps to verify the image inference results. You can judge whether lora works based on this.
